export const fishes = [
  { name: "Рыба-ангел", id: "angel" },
  { name: "Антиас", id: "antias" },
  { name: "Групер", id: "grupper" },
  { name: "Дельфин", id: "dolphin" },
  { name: "Рыба-попугай", id: "parrot" },
  { name: "Каранкс", id: "tuna" },
  { name: "Рыба-солдат", id: "solders" },
  { name: "Зебрасома", id: "zebrosoma" },
  { name: "Рыба-клоун", id: "nemo" },
  { name: "Цезии", id: "cezii" },
  { name: "Кузовок", id: "kuzovok" },
  { name: "Рыба-флейта", id: "flute" },
  { name: "Дюгонь", id: "dugon" },
  { name: "Платаксы", id: "platex" },
  { name: "Шептуны", id: "whisperers" },
  { name: "Сколопсис", id: "scolopsis" },
  { name: "Наполеон", id: "napoleon" },
  { name: "Губановые", id: "lipsfish" },
  { name: "Кабубы", id: "kabuba" },
  { name: "Расписные алутеры", id: "aluter" },
  { name: "Аротрон", id: "arototron" },
  { name: "Барракуда", id: "baracuda" },
  { name: "Рыба-крокодил", id: "crocodile" },
  { name: "Рыба-молот", id: "hammerfish" },
  { name: "Крылатка", id: "lionfish" },
  { name: "Длиннокрылая акула", id: "longwingedfish" },
  { name: "Мурена", id: "murena" },
  { name: "Морская змея", id: "seasnake" },
  { name: "Рифовая акула", id: "sharksblackfeather" },
  { name: "Тупорылая акула", id: "sharkscow" },
  { name: "Акула мако", id: "sharksmaco" },
  { name: "Акула-нянька", id: "sharksnuss" },
  { name: "Белая акула", id: "sharkswhite" },
  { name: "Акула-зебра", id: "sharkszebra" },
  { name: "Тигровая акула", id: "tiggerfish" },
  { name: "Китовая акула", id: "whalesharks" },
  { name: "Рыба-камень", id: "stonefish" },
  { name: "Скат-хвостокол", id: "skat" },
  { name: "Орляк", id: "skatorlyak" },
  { name: "Манта", id: "skatmantu" },
  { name: "Тилозур", id: "tulozure" },
  { name: "Хирург", id: "surgeon" },
  { name: "Балистод", id: "balistod" },
  { name: "Спинорог", id: "spinorog" },
  { name: "Черепаха", id: "turtles" },
  { name: "Осьминог", id: "octopus" },
  { name: "Кальмар", id: "squids" },
  { name: "Медузы", id: "jellyfish" },
  { name: "Кораллы", id: "corals" },
  { name: "Моллюски", id: "mollusks" },
  { name: "Морские ежи", id: "hedgehog" },
  { name: "Морская звезда", id: "stars" }
];
